Верстка страницы каталога дз 1 ч. 2
htmlacademy-htmlcss/1873103-sedona-32 pull request #3
Opened 2021-09-28 19:11 UTC by OksanaAzarnova

2021-09-29 05:24 UTC, baileys-li requested changes
Хорошая работа

2021-09-29 05:24 UTC, baileys-li commented on Catalog.html
> +        <h2 class="visually-hidden">Список гостиниц Седоны</h2>
Список гостиниц всё-таки в следующей секции, поэтому либо увеличивать уровень следующих заголовков, либо переименовать этот в «Фильтры» 
![image](https://user-images.githubusercontent.com/47776594/135205899-2a453aef-573a-4549-8a7f-1c719eab1219.png)

2021-09-29 05:24 UTC, baileys-li commented on Catalog.html
> +              />
```suggestion
              <input
                class="visually-hidden control-input"
                type="checkbox"
                name="swimming pool"
                checked
              />
```

2021-09-29 05:24 UTC, baileys-li commented on Catalog.html
> +              />
```suggestion
              <input
                class="visually-hidden control-input"
                type="checkbox"
                name="parking space"
                checked
              />
```

2021-09-29 05:24 UTC, baileys-li commented on Catalog.html
> +              />
В этом филдсете радиокнопки. Чтобы они работали корректно, нужен один и тот же `name`, но разные `value`. Первый элемент по умолчанию `checked`
```suggestion
              <input
                class="visually-hidden control-input"
                type="radio"
                name="category"
                value="Гостиница"
                checked
              />
```

2021-09-29 05:24 UTC, baileys-li commented on Catalog.html
> +              />
для второго так же, но с другим значением по умолчанию
```suggestion
              <input
                class="catalog-filter-input"
                type="number"
                name="min-price"
                value="0"
                min="0" 
                max="10000"
              />
```

2021-09-29 05:24 UTC, baileys-li commented on Catalog.html
> +          <button class="button" type="submit">Сбросить</button>
```suggestion
          <button class="button" type="reset">Сбросить</button>
```

2021-09-29 05:24 UTC, baileys-li commented on Catalog.html
> +              <option value="cheap">Сначала дешёвое</option>
```suggestion
              <option value="cheap" selected>Сначала дешёвое</option>
```

2021-09-29 05:24 UTC, baileys-li commented on Catalog.html
> +                <span class="visually-hidden">Не пойму, что значит иконка</span>
Крупная карточка

2021-09-29 05:24 UTC, baileys-li commented on Catalog.html
> +                  </a>
Лучше сделать двумя ссылками, потому что будет сложновато подстроить под сетки

2021-09-29 05:24 UTC, baileys-li commented on Catalog.html
> +                    alt="Фото  рейтинги Amara Resort"
```suggestion
                    alt="4 звезды"
```

2021-09-29 05:24 UTC, baileys-li commented on Catalog.html
> +              <a class="pagination-link" href="#">5</a>
```suggestion
              <a class="pagination-link" href="#">…</a>
```

2021-09-29 05:24 UTC, baileys-li commented on Catalog.html
> +          </select>
нужно связать лейбл с выбором. Либо вложив
```suggestion
          <label class="show">Гостиниц на странице
            <select class="show-list">
              <option class="show-item" selected>4</option>
              <option class="show-item">8</option>
              <option class="show-item">16</option>
            </select>
          </label>
```
Либо с помощью id
```suggestion
          <label class="show" for="show-list">Гостиниц на странице</label>
          <select class="show-list" id="show-list">
            <option class="show-item">4</option>
            <option class="show-item">8</option>
            <option class="show-item">16</option>
          </select>
```

2021-09-29 19:00 UTC, OksanaAzarnova commented on Catalog.html
> +      <img src="#" alt="лого академии" class="foot-logo" />
Исправила

2021-09-29 19:01 UTC, OksanaAzarnova commented on index.html
> +            <a class="navigation-link" href="Catalog.html">Гостиницы</a>
Исправила

2021-09-29 19:02 UTC, OksanaAzarnova commented on index.html
>        <p class="visually-hidden">Прекрасные горы седоны. Фото для фона</p>
Фразу фото для фона убрала

2021-09-29 19:03 UTC, OksanaAzarnova commented on index.html
>        <p class="visually-hidden">Прекрасные горы седоны. Фото для фона</p>
Вообще убрала

2021-09-29 19:05 UTC, OksanaAzarnova commented on Catalog.html
> +            <a class="navigation-link" href="gostinica.html">Гостиницы</a>
<a class="navigation-link" href="сatalog.html">Гостиницы</a> исправила

2021-09-29 19:08 UTC, OksanaAzarnova commented on Catalog.html
> +        <img class="logo" src="#" alt="логотип" />
Исправила

2021-09-29 19:23 UTC, OksanaAzarnova commented on Catalog.html
> +                    alt="Фото  рейтинги Amara Resort"
Исправила

2021-09-29 19:25 UTC, OksanaAzarnova commented on Catalog.html
> +          </select>
Исправила

2021-09-30 00:26 UTC, baileys-li approved these changes

2021-09-30 00:26 UTC, baileys-li commented on сatalog.html
> +      />
```suggestion
      <a href="https://htmlacademy.ru/">
        <img src="" alt="лого академии" class="foot-logo"/>
      </a>
      
```

2021-09-30 00:26 UTC, merged